### ISSUE TITLE
Error in event handler for runtime.onMessage

### ISSUE THREAD

**Issue by conorpp** [jpouellet/scholar-renamer#6]
When I look at my classes and right click one of them, and then select the "Edit Scholar Tab Name" it doesn't work and the JS console prints this message:

Error in event handler for runtime.onMessage: TypeError: Cannot read property 'parentElement' of undefined
    at chrome-extension://eioglgfcfkhhmkpjcjhepgcbhadcpcam/inject.js:34:18

This prints immediately after the click on "Edit Scholar Tab Name"
![untitled](https://cloud.githubusercontent.com/assets/3942133/7152132/8aad59e2-e303-11e4-91d8-300541535357.png)

**Comment by jpouellet** [comment]
Yeah, that's not a tab, that's the "More Sites" view. Still unimplemented, see #2 & #4. (correct) pull requests welcome :)
